### ISSUE TITLE
Notation for the central charge.

### ISSUE THREAD

**Issue by ardonne** [anyonwiki/anyonwiki.github.io#13]
In the series of fusion rings, we (will) often make the link to CFTs, and their central charge (not modulo 8)
The central charge from the anyon models is 'only' defined modulo 8. I propose to call the latter the 'topological central charge', denoted by $c_{\rm top}$. Then we can use 'central charge', denoted by $c$ for the 'ordinary' central charge.

**Comment by anyonwiki** [comment]
Sounds fine to me :)
Maybe we should, in the future, also make a page about central charge and another one about CFT

**Comment by ardonne** [comment]
sounds good
